# Field constants
FIELD_FROM = "From"
FIELD_TO = "To"
FIELD_SUBJECT = "Subject"
FIELD_MESSAGE = "Message"
FIELD_RECEIVED = "Received"

# Predicate constants
PREDICATE_CONTAINS = "Contains"
PREDICATE_DOES_NOT_CONTAIN = "DoesNotContain"
PREDICATE_EQUALS = "Equals"
PREDICATE_DOES_NOT_EQUAL = "DoesNotEqual"
PREDICATE_LESS_THAN_DAYS = "LessThanDays"
PREDICATE_GREATER_THAN_DAYS = "GreaterThanDays"
PREDICATE_LESS_THAN_MONTHS = "LessThanMonths"
PREDICATE_GREATER_THAN_MONTHS = "GreaterThanMonths"

# Rule predicate constants
RULE_PREDICATE_ALL = "All"
RULE_PREDICATE_ANY = "Any"

# Field type groupings for validation
STRING_FIELDS = {FIELD_FROM, FIELD_TO, FIELD_SUBJECT, FIELD_MESSAGE}
DATE_FIELDS = {FIELD_RECEIVED}

STRING_PREDICATES = {PREDICATE_CONTAINS, PREDICATE_DOES_NOT_CONTAIN, PREDICATE_EQUALS, PREDICATE_DOES_NOT_EQUAL}
DATE_PREDICATES = {PREDICATE_LESS_THAN_DAYS, PREDICATE_GREATER_THAN_DAYS, PREDICATE_LESS_THAN_MONTHS, PREDICATE_GREATER_THAN_MONTHS}

# Database constants
BATCH_SIZE_DEFAULT = 1000
DAYS_PER_MONTH = 30
DEFAULT_OFFSET = 0
DEFAULT_LIMIT = 20

# Error messages
ERROR_INVALID_FIELD = "Invalid field: {}"

# Gmail API constants
GMAIL_BATCH_SIZE = 20
MAX_MESSAGES_TO_PROCESS = 20
MAX_PAGES_TO_PROCESS = 10
MAX_RESULTS_PER_PAGE = 50

# Action constants
ACTION_MARK_READ = "read"
ACTION_MARK_UNREAD = "unread"
ACTION_MOVE = "move"
